spring:
  application:
    name: blog-center
  # import zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0 # 100%
  datasource:
    url: jdbc:mysql://${audit.datasource.ip}:3306/blog-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: ${audit.datasource.username}
    password: ${audit.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #
  typeAliasesPackage: com.iris.blog.entity
  global-config:
    db-config:
      id-type: auto

server:
  port: 7010

 #Eureka
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka

swagger:
  butler:
    auto-generate-from-zuul-routes: true
    generate-routes: user,file
    apiDocsPath: v2/api-docs


