spring:
  application:
    name: service-zuul
  # import zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0 #\u914D\u7F6E100%\u7684\u6982\u8BBA\u5C06\u94FE\u8DEF\u7684\u6570\u636E\u4E0A\u4F20\u7ED9zipkin server\uFF0C\u9ED8\u8BA40.1


# Eureka \u5BA2\u6237\u7AEF\u914D\u7F6E
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka #eureka

zlt:
  oauth2:
    token:
      store:
        type: redis
  security:
    ignore:
      # 忽略认证的地址
      httpUrls: >
        /api-uaa/oauth/**,
        /api-uaa/validata/**,
        /api-uaa/css/**,
        /api-uaa/images/**,
        /api-uaa/js/**,
        /api-user/users-anon/**,
        /login.html,
        /user/login
    auth:
      urlPermission:
        #是否开启url级别权限
        enable: false
        #配置只进行登录认证，不进行url权限认证的api
        ignoreUrls: >
          /api-user/menus/current,
          /api-user/users/current,
          /api-log/requestStat
        #白名单
        includeClientIds:
        - webApp
      renew:
        #是否开启token自动续签（目前只有redis实现）
        enable: true
        #白名单
        includeClientIds:
        - webApp
  gateway:
    #网关动态路由
    dynamicRoute:
      enabled: true

zuul:
  ribbon-isolation-strategy: thread
  ribbon:
    eager-load:
      enabled: true
    threadPool:
      useSeparateThreadPools: true
      threadPoolKeyPrefix: api-gateway
  #关闭重试
  retryable: false
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Access-Control-Allow-Methods
  add-host-header: true
  routes:
    auth:
      path: /api-uaa/**
      service-id: oauth-center-server
      strip-prefix: true
      sensitive-headers: '*'
      custom-sensitive-headers: true
    auth-login-page:
      path: /login.html
      service-id: oauth-center-server
      strip-prefix: true
      sensitive-headers: '*'
      custom-sensitive-headers: true
    auth-login-process:
      path: /user/login
      service-id: oauth-center-server
      strip-prefix: true
      sensitive-headers: '*'
      custom-sensitive-headers: true
    auth-login-token:
      path: /oauth/token
      service-id: oauth-center-server
      strip-prefix: true
      sensitive-headers: '*'
      custom-sensitive-headers: true
    auth-login-authorize:
      path: /oauth/authorize
      service-id: oauth-center-server
      strip-prefix: true
      sensitive-headers: '*'
      custom-sensitive-headers: true
    auth-check-process:
      path: /oauth/check_token
      service-id: oauth-center-server
      strip-prefix: true
      sensitive-headers: '*'
      custom-sensitive-headers: true
    user:
      path: /api-user/**
      service-id: user-center
      strip-prefix: true
      sensitive-headers: '*'
      custom-sensitive-headers: true
    file:
      path: /api-file/**
      service-id: file-center
      strip-prefix: true
      sensitive-headers: '*'
      custom-sensitive-headers: true
    log:
      path: /api-log/**
      service-id: log-center
      strip-prefix: true
      sensitive-headers: '*'
      custom-sensitive-headers: true
    generator:
      path: /api-generator/**
      service-id: code-generator
      strip-prefix: true
      sensitive-headers: '*'
      custom-sensitive-headers: true
    search:
      path: /api-search/**
      service-id: search-center
      strip-prefix: true
      sensitive-headers: '*'
      custom-sensitive-headers: true
  ssl-hostname-validation-enabled: false

hystrix:
  threadpool:
    default:
      coreSize: 100
      maximumSize: 2000
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: -1
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

swagger:
  butler:
    auto-generate-from-zuul-routes: true
    generate-routes: user,file
    apiDocsPath: v2/api-docs